name: myriad
favicon: null
layout_spectrum: 0.19246166967786849
typography_spectrum: 0.043461284367367625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10141a'
    - '#3e5d6b'
    - '#4af5db'
    - '#fafafa'
    - '#f22f38'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.1318177250213921
  rhythmicContrast: 0.5565056670457125
purpose: []
